; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = drupal

; Modules
projects[] = admin_menu

projects[] = ctools

projects[] = devel

projects[] = entity

projects[] = exclude_node_title

projects[] = media

projects[] = jquery_colorpicker

projects[] = jquery_update

projects[] = less

projects[] = libraries

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[md_slider][download][type] = "get"
;projects[md_slider][download][url] = "http://server.salesmanvideo.com/sites/server.salesmanvideo.com/files/md_slider.zip"
;projects[md_slider][location] = ""
;projects[md_slider][type] = "module"
;projects[md_slider][version] = "2.15"
projects[md_slider][location] = http://fserver.mastersalesvideos.com/fserver

projects[] = nivo_slider

projects[] = pathauto

projects[] = profile2

projects[] = rules

projects[] = site_map

projects[] = token

projects[] = views

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print][download][type] = ""
;projects[print][download][url] = ""
;projects[print][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_epub][download][type] = ""
;projects[print_epub][download][url] = ""
;projects[print_epub][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_epub_phpepub][download][type] = ""
;projects[print_epub_phpepub][download][url] = ""
;projects[print_epub_phpepub][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_mail][download][type] = ""
;projects[print_mail][download][url] = ""
;projects[print_mail][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_pdf][download][type] = ""
;projects[print_pdf][download][url] = ""
;projects[print_pdf][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_pdf_dompdf][download][type] = ""
;projects[print_pdf_dompdf][download][url] = ""
;projects[print_pdf_dompdf][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_pdf_mpdf][download][type] = ""
;projects[print_pdf_mpdf][download][url] = ""
;projects[print_pdf_mpdf][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_pdf_tcpdf][download][type] = ""
;projects[print_pdf_tcpdf][download][url] = ""
;projects[print_pdf_tcpdf][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_pdf_wkhtmltopdf][download][type] = ""
;projects[print_pdf_wkhtmltopdf][download][url] = ""
;projects[print_pdf_wkhtmltopdf][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[print_ui][download][type] = ""
;projects[print_ui][download][url] = ""
;projects[print_ui][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[session_expire][download][type] = ""
;projects[session_expire][download][url] = ""
;projects[session_expire][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

;projects[mastersalesvideo][download][type] = "git"
;projects[mastersalesvideo][download][url] = "https://github.com/me336408/MSV.git"
;projects[mastersalesvideo][directory_name] = "mastersalesvideo"
;projects[mastersalesvideo][type] = "theme"
projects[mastersalesvideo][location] = http://fserver.mastersalesvideos.com/fserver

;projects[Porto][download][type] = "get"
;projects[Porto][download][url] = "http://server.salesmanvideo.com/sites/server.salesmanvideo.com/files/Porto.zip"
;projects[Porto][type] = "theme"
projects[porto][location] = http://fserver.mastersalesvideos.com/fserver

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[Porto_sub][download][type] = "get"
;projects[Porto_sub][download][url] = "http://server.salesmanvideo.com/sites/server.salesmanvideo.com/files/Porto_sub.zip"
;projects[Porto_sub][type] = "theme"
projects[porto_sub][location] = http://fserver.mastersalesvideos.com/fserver

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[nivo-slider][download][type] = "git"
libraries[nivo-slider][download][url] = "https://github.com/gilbitron/Nivo-Slider.git"
libraries[nivo-slider][directory_name] = "nivo-slider"
libraries[nivo-slider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = "get"
libraries[lessphp][download][url] = "https://github.com/oyejorge/less.php/archive/master.zip"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorpicker][download][type] = "get"
libraries[colorpicker][download][url] = "http://www.eyecon.ro/colorpicker/colorpicker.zip"
libraries[colorpicker][directory_name] = "colorpicker"
libraries[colorpicker][type] = "library"
